library(igraph)
library(devtools)
library(GenomicRanges)
library(chromunity)
# library(gUtils)
# library(ComplexHeatmap)
# devtools::install_github('mskilab/gChain')
# library(gChain)
# devtools::install_github('mskilab/skitools')
# library(skitools)
devtools::install("/gpfs/commons/groups/gursoy_lab/ajoglekar/Support/Software/Packages/R/sourceInstall_fromGit/chromunity/")
# library(chromunity)
